### ISSUE TITLE
Unable to serialise CallRecord types

### ISSUE THREAD

**Issue by cowlinb6** [microsoft/kiota-serialization-json-dotnet#217]
Similar issue to #212 but with CallRecord types.

When attempting to serialise a CallRecord type:
```
var callRecord = await _graphServiceClient.Communications.CallRecords[id]
    .GetAsync((config) =>
    {
        config.QueryParameters.Expand = new string[] { "sessions($expand=segments)" };
    });
var raw = KiotaJsonSerializer.SerializeAsString<CallRecord>(callRecord);
```

This fails with the error below:
```
System.InvalidOperationException: AdditionalData can not be null
   at Microsoft.Graph.Models.Entity.get_AdditionalData()
   at Microsoft.Graph.Models.Entity.Serialize(ISerializationWriter writer)
   at Microsoft.Graph.Models.CallRecords.CallRecord.Serialize(ISerializationWriter writer)
   at Microsoft.Kiota.Serialization.Json.JsonSerializationWriter.WriteObjectValue[T](String key, T value, IParsable[] additionalValuesToMerge)
   at Microsoft.Kiota.Abstractions.Serialization.KiotaSerializer.SerializeAsStream[T](String contentType, T value)
   at Microsoft.Kiota.Abstractions.Serialization.KiotaSerializer.SerializeAsString[T](String contentType, T value)
   at Microsoft.Kiota.Abstractions.Serialization.KiotaJsonSerializer.SerializeAsString[T](T value)
   at TeamsPbxTest.GraphClient.GetCallRecord(String id) in C:\Users\Ben\source\code\TeamsPbxTest\TeamsPbxTest\GraphClient.cs:line 177
```

How should I be serialising this type?

**Comment by andrueastman** [comment]
Thanks for raising this @cowlinb6 

I suspect the error you're seeing is related to https://github.com/microsoft/kiota/pull/4514. However, `AdditionalData` should be automatically initialized when the object is created in the constructor. Do you still get the error if you add the line below before serializing?

```cs
callRecord.AdditionalData = new();
```

**Comment by cowlinb6** [comment]
If I add this:

```
callRecord.AdditionalData = new Dictionary<string, object>();
var raw = KiotaJsonSerializer.SerializeAsString<CallRecord>(callRecord);
```

Then it fixes the exception but I only get this in the response:

![image](https://github.com/microsoft/kiota-serialization-json-dotnet/assets/12410874/cfb6a907-8751-4339-b438-d3192417f7dc)

**Comment by cowlinb6** [comment]
Yes this does work.

Thanks @andrueastman for the quick response on this
